apiVersion: apps/v1
kind: Deployment
metadata:
  name: mts-angular
  labels:
    app: mts
spec:
  selector:
    matchLabels:
      app: mts
      tier: angular
  replicas: 1
  template:
    metadata:
      labels:
        app: mts
        tier: angular
    spec:
      containers:
      - name: angular
        image: registry.cloud.okteto.net/sujith-mn/mts-angular
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80        
---
 
apiVersion: v1
kind: Service
metadata:
  name: mts-angular
  annotations:
    dev.okteto.com/auto-ingress: "true"  
  labels:
    app: mts
    tier: angular
spec:
  type: ClusterIP  
  ports:
  - name: mts-angular
    port: 80
  selector:
    app: mts
    tier: angular

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mts-java
  annotations:
    dev.okteto.com/auto-ingress: "true"    
  labels:
    app: mts
spec:
  selector:
    matchLabels:
      app: mts
      tier: java
  replicas: 1
  template:
    metadata:
      labels:
        app: mts
        tier: java
    spec:
      containers:
      - name: angular
        image: registry.cloud.okteto.net/sujith-mn/mts-java
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8081        
---
 
apiVersion: v1
kind: Service
metadata:
  name: mts-java
  labels:
    app: mts
    tier: java
spec:
  type: ClusterIP  
  ports:
  - name: mts-java
    port: 8081
  selector:
    app: mts
    tier: java

---
