apiVersion: apps/v1
kind: Deployment
metadata:
  name: mts-angular
  labels:
    app: mts
spec:
  selector:
    matchLabels:
      app: mts
      tier: angular
  replicas: 1
  template:
    metadata:
      labels:
        app: mts
        tier: angular
    spec:
      containers:
      - name: angular
        image: isandesh/my-thai-star-angular:latest
        imagePullPolicy: Always
---
 
apiVersion: v1
kind: Service
metadata:
  name: mts-angular
  labels:
    app: mts
    tier: angular
spec:
  type: ClusterIP  
  ports:
  - name: "mts-angular"
    port: 80
  selector:
    app: mts
    tier: angular
