
name: Create and publish a Docker image

on:
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mythaistar-java

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Build and push Docker image  
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ env.IMAGE_NAME }}
          registry: ghcr.io
          tags: v2, latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: java/Dockerfile.githubactions
